const images = {
  "woman-avatar": require('./images/woman-avatar.png'),
  "woman-silhouette": require('./images/woman-silhouette.png'),
  "loading_md": require('./images/loading.gif'),
  "loading_sm": require('./images/loading-sm.gif'),
  "avatar": require('./images/avatar.jpg'),
  "mail": require('./images/mail.png'),
  "password": require('./images/password.png'),
  "fb": require('./images/fb.png'),
  "google": require('./images/google.png'),
  "user": require('./images/user.png'),
  "airbnb": require('./images/airbnb.png'),
  "cashhub": require('./images/cashhub.jpeg'),
  "register": require('./images/register.jpg'),
  "selfie": require('./images/selfie.png'),
  "success": require('./images/success.png'),
  "wallet": require('./images/wallet.png'),
  "logo_sm": require('./images/cash_hub_logo_sm.png'),
  "logo_2": require('./images/logo_2.png'),
  "logo_3": require('./images/logo_3.png'),
  "car_avatar": require('./images/car_avatar.png'),
  "benz": require('./images/benz.png'),

  "car_front": require('./images/car_front.jpg'),
  "car_back": require('./images/car_back.jpg'),
  "car_left_side": require('./images/car_left_side.jpeg'),
  "car_right_side": require('./images/car_right_side.jpg'),

}
export default images
